#!/usr/bin/env groovy

@Library('jenkins-shared-library')_
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }

    stages {
        stage('init') {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }

        stage('build jar') {
            steps {
                script {
                    gv.buildjar()
                }
            }
        }
        
        stage('build images') {
            steps {
                script {
                    buildImage()
                }
            }
        }
    }
}
